"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = 'django-insecure-2%qcpf%9c8hu89c#wo*-kcfs7@fi^lbx6i_ygdz_pnqs89)rjr'

DEBUG = True

ALLOWED_HOSTS = [
    '10.0.2.2',
    'localhost',
    '127.0.0.1'
]



INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
        "http://localhost:8081", # Metro Bundler
        "http://127.0.0.1:8081",
       
    ]

CORS_ALLOW_HEADERS = [
        'accept',
        'accept-encoding',
        'authorization', 
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
    ]

CORS_ALLOW_METHODS = [
        'DELETE',
        'GET',
        'OPTIONS',
        'PATCH',
        'POST',
        'PUT',
    ]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'app_db',
        'USER': 'emma',
        'PASSWORD': '636363636363',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ALLOWED_EMAIL_DOMAINS = [
    'ucr.ac.cr',
    'una.cr',
    'uned.cr',
    'utn.ac.cr',
    'tec.ac.cr',
    'earth.ac.cr',
    'incase.edu',
    'ulatina.ac.cr',
    'ulacit.ac.cr',
    'veritas.cr',
    'uam.cr',
    'uci.ac.cr',
    'uaca.cr',
    'uiberoamerica.cr',
    'ucienciasmedicas.cr',
    'ucartago.cr',
    'usj.cr',
    'ucienciasyarte.cr',
    'ufsjt.cr',
    'umagister.cr',
    'uip.cr',
    'ucsa.cr',
    'upapa.cr',
    'uisil.cr',
    'uem.cr',
    'uicr.cr',
    'uea.cr',
    'uca.cr',
    'uct.cr',
    'usac.cr',
    'usc.cr',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

SIMPLE_JWT = {
      'ACCESS_TOKEN_LIFETIME': timedelta(hours=1), 
      'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
  }

MEDIA_URL = '/uploads/' 

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads') 

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
